# Generated by Django 4.2.3 on 2023-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='card_image',
        ),
        migrations.AddField(
            model_name='cards',
            name='image',
            field=models.ImageField(default='image/none/noimg.jpg', upload_to='images'),
        ),
    ]
