# Generated by Django 4.2.3 on 2023-08-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0002_remove_cards_card_image_cards_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='image/none/noimg.jpg', upload_to='images')),
            ],
        ),
    ]
