# Generated by Django 4.2.3 on 2023-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0003_cards1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
