# Generated by Django 4.2.3 on 2023-08-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0004_cards_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards1',
        ),
        migrations.AlterField(
            model_name='cards',
            name='value',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
