# Generated by Django 4.2.3 on 2023-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0006_cards_suit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BB_100bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_name', models.CharField(max_length=100)),
                ('suited', models.CharField(max_length=3)),
                ('card1', models.CharField(max_length=1)),
                ('card2', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SB_100bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_name', models.CharField(max_length=100)),
                ('suited', models.CharField(max_length=3)),
                ('card1', models.CharField(max_length=1)),
                ('card2', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='utg_100bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_name', models.CharField(max_length=100)),
                ('suited', models.CharField(max_length=3)),
                ('card1', models.CharField(max_length=1)),
                ('card2', models.CharField(max_length=1)),
            ],
        ),
    ]
