# Generated by Django 4.2.3 on 2023-08-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0008_bb_100bb_action_sb_100bb_action_utg_100bb_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='utg_100bb',
            new_name='U_T_G_100bb',
        ),
    ]
