# Generated by Django 4.2.3 on 2023-08-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0009_rename_utg_100bb_u_t_g_100bb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='U_T_G_100bb',
            new_name='utg_100bb',
        ),
    ]
