# Generated by Django 4.2.4 on 2023-08-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0016_alter_bb_100bb_card1_alter_bb_100bb_card2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
