# Generated by Django 4.2.4 on 2023-08-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerMain', '0017_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='attempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoring',
            name='correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoring',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
